### ISSUE TITLE
find_orb ephemeris just printing ................

### ISSUE THREAD

**Issue by Mikea1985** [Bill-Gray/find_orb#18]
I was getting used to using find_orb, but then somehow I broke it (kept getting an error about a missin ps_1996.dat file that was totally there), so I deleted everything and installed again. This time, producing ephemerides (with the `C` option set to `observables`) just returns a single line of periods instead of the ephemerides requested, like so:
```
#(568) Mauna Kea: Col3N10
Date (UTC)   RA              Dec          mag " sig PA
---- -- --  -------------   -----------   --- ---- ---
................
```

Given that this was the first thing that I did after re-installing and that it worked for the same (mpc-formatted) astrometry file before I broke the previous install, I don't really understand why this is happening...

**Comment by Bill-Gray** [comment]
First,  thanks for the reminder on the missing ps_1996.dat file.  I don't think you actually broke anything.  I vaguely recall seeing that error message once.  I _think_ it comes up when you've set up JPL ephems,  but provide observations or request ephemerides outside the range covered by the JPL file.
Second : usually,  when that happens to me,  it's because the 'U' option ("suppress unobservables") is ticked,  and by the selected criteria,  the object is unobservable for all ephemeris points.  That is to say,  it's either below the horizon,  or the sun is up,  or it's fainter than the faint limit (the 'F' option in the Make Ephemeris menu).
I should probably have the code look at the number of lines output and,  if that number is zero,  give a message such as "No ephemeris output;  object was too faint,  or below horizon,  or in daylight for the times specified.  Check ephemeris options."

**Comment by Mikea1985** [comment]
>.< Thanks, that was it. The default value for the 'F' limit is 22; all my objects are fainter, and I somehow didn't notice the value there.

**Comment by rankinstudio** [comment]
Running fo, or find_orb:
I have the latest jpl file, it is in the reference file, and fo still gives the ps_1996.dat file error.
The file ps_1996.dat is missing ect...
The file elp82.dat is missing ect...
Both are in the directory and referenced correctly. 
It shows up in a red warning banner at the top when running find_orb (obs) that no JPL DE ephemeris file was loaded.
