### ISSUE TITLE
unable to compile find_orb : no curses.h

### ISSUE THREAD

**Issue by MADECICCO** [Bill-Gray/find_orb#30]
It seems there is no curses.h file 

`findorb.cpp:40:13: fatal error: curses.h: No such file or directory
    #include "curses.h"`
Ubuntu 184.4.

**Comment by Bill-Gray** [comment]
Hmmm... that should only happen if the wide-character version of the ncurses development library,  libncursesw5-dev (may be libncursesw6-dev) isn't installed.  I don't remember which version is used on 18.04;  either will work.

In a few places (see,  for example,  `jpleph.cpp` in the `jpl_eph` repo),  I've made use of the `has_include()` directive so that I can show a more informative error message.  In this case,  it could be I should add something like
```
#if defined( __has_include) && !__has_include(<curses.h>)
   #error   \
     'curses.h' not found.  Install libncursesw6-dev (wide-character\
     version of the ncurses library) and try again;  it should work.\
    It may be libncursesw5-dev on older systems.
#endif
```
I've occasionally wished there was a cleaner way to tell people,  "Thus-and-such dependency wasn't found;  here's what to do about it."  The above is pretty good,  though.

**Comment by MADECICCO** [comment]
Yeah, `sudo  apt get install libncurses5-dev libncursesw5-dev` solved this issue.
Thanks!
